services:
  - type: web
    name: photo-album
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /photos
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
